# 开发环境配置
server:
  port: 8080
# 数据源配置
spring:
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    database: 11
xxl:
  job:
    accessToken: 0e8701d4307a445c90b4e70565893a95
    adminAddresses: http://127.0.0.1:7040
    applicationName: 调度平台-开发环境
    executor:
      appName: xxl-job
      title: xxl-job
      autoCreateJob: true
      autoStartJob: true
      ip: ''
      logpath: /data/logs/xxl-job/jobhandler
      logretentiondays: 3
      port: 7998

