version: '2.2'
services:
  smart-job:
    image: wuque1024/smart-job:v2.0.0
    container_name: smart-job
    network_mode: host
    restart: always
    dns:
      - 223.5.5.5
      - 223.6.6.6
    volumes:
      - /data/logs:/data/logs
      - /data/config:/data/config
    environment:
      - JAVA_XMX=512
      - JAVA_XMN=512
      - GcLogPath=/data/logs
      - ACTIVE_PROFILE=prod
      - mysql_ip=127.0.0.1
      - mysql_user=root
      - mysql_password=123456
      - mysql_port=3306
      - redis_ip=127.0.0.1
      - redis_port=6379
      - redis_password=123456
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7040/actuator/health"]
      interval: 30s
      timeout: 20s
      retries: 3
